package com.shadowdict.domain

import com.shadowdict.data.local.entity.SubLine

/** The four fixed learning stages (spec §4). */
enum class Stage { LISTEN, MEANING, DICTATION, IMPRINT }

/** A line queued for study, tagged as review or new. */
data class StudyItem(
    val line: SubLine,
    val isReview: Boolean,
)

object StageFlow {
    /**
     * Ordered stages for a line. Auto-generated subtitles skip DICTATION
     * (spec §2, §4), running LISTEN -> MEANING -> IMPRINT.
     */
    fun stagesFor(isAutoGenerated: Boolean): List<Stage> =
        if (isAutoGenerated) {
            listOf(Stage.LISTEN, Stage.MEANING, Stage.IMPRINT)
        } else {
            listOf(Stage.LISTEN, Stage.MEANING, Stage.DICTATION, Stage.IMPRINT)
        }

    /** Number of LISTEN replays required to pass stage 1 (spec §4). */
    const val LISTEN_REPLAYS_REQUIRED = 3
}
