package com.shadowdict.data

import com.shadowdict.core.chunk.ChunkSplitter
import com.shadowdict.core.subtitle.ParsedLine
import com.shadowdict.data.local.ShadowDictDatabase
import com.shadowdict.data.local.entity.DailySession
import com.shadowdict.data.local.entity.LineStatus
import com.shadowdict.data.local.entity.Source
import com.shadowdict.data.local.entity.SourceType
import com.shadowdict.data.local.entity.SubLine
import com.shadowdict.domain.SrsScheduler
import com.shadowdict.data.local.entity.Attempt
import kotlinx.coroutines.flow.Flow
import java.time.LocalDate

/** Central data facade over the DAOs (spec §3, §4, §8). */
class ShadowDictRepository(private val db: ShadowDictDatabase) {

    private val sourceDao = db.sourceDao()
    private val lineDao = db.subLineDao()
    private val sessionDao = db.dailySessionDao()
    private val attemptDao = db.attemptDao()

    // ── Sources ──

    fun observeSources(): Flow<List<Source>> = sourceDao.observeAll()
    fun observeMasteredCount(): Flow<Int> = lineDao.observeMasteredCount()
    suspend fun getSource(id: Long): Source? = sourceDao.getById(id)
    fun observeLines(sourceId: Long): Flow<List<SubLine>> = lineDao.observeBySource(sourceId)
    suspend fun deleteSource(id: Long) = sourceDao.delete(id)

    /**
     * Import a source and its lines, applying chunk splitting (spec §4).
     * Returns the new source id.
     */
    suspend fun addSource(
        title: String,
        type: SourceType,
        mediaUri: String?,
        subtitleFileName: String?,
        isAutoGenerated: Boolean,
        parsedLines: List<ParsedLine>,
        chunkThreshold: Int,
        now: Long = System.currentTimeMillis(),
    ): Long {
        val drafts = buildLines(parsedLines, chunkThreshold)
        val source = Source(
            title = title,
            type = type,
            mediaUri = mediaUri,
            subtitleFileName = subtitleFileName,
            isAutoGenerated = isAutoGenerated,
            totalLines = drafts.size,
            createdAt = now,
            lastStudiedAt = null,
        )
        val sourceId = sourceDao.insert(source)

        // First pass: insert all rows.
        val toInsert = drafts.map { it.line.copy(sourceId = sourceId) }
        val ids = lineDao.insertAll(toInsert)

        // Second pass: link chunk siblings to the first id of their group.
        drafts.forEachIndexed { index, draft ->
            val groupFirst = draft.groupFirstIndex
            if (groupFirst != null) {
                val current = lineDao.getById(ids[index])!!
                lineDao.update(current.copy(chunkParentId = ids[groupFirst]))
            }
        }
        return sourceId
    }

    /** A pending line plus, for chunks, the list index of its group's first chunk. */
    private data class LineDraft(val line: SubLine, val groupFirstIndex: Int?)

    /**
     * Flatten parsed lines into SubLines with sequential order indexes, splitting
     * long lines (spec §4). Each chunk carries the index of the first chunk in its
     * group so chunkParentId can be set once row ids are known.
     */
    private fun buildLines(parsed: List<ParsedLine>, chunkThreshold: Int): List<LineDraft> {
        val out = ArrayList<LineDraft>()
        var order = 0
        for (p in parsed) {
            val words = p.text.trim().split(Regex("\\s+")).filter { it.isNotEmpty() }
            if (words.size <= chunkThreshold) {
                out += LineDraft(
                    SubLine(
                        sourceId = 0,
                        orderIndex = order++,
                        startMs = p.startMs,
                        endMs = p.endMs,
                        textEn = p.text,
                        textKo = null,
                        chunkParentId = null,
                        wordCount = words.size,
                    ),
                    groupFirstIndex = null,
                )
            } else {
                val pieces = ChunkSplitter.split(p.text, p.startMs, p.endMs, chunkThreshold)
                val groupFirstIndex = out.size
                for (piece in pieces) {
                    out += LineDraft(
                        SubLine(
                            sourceId = 0,
                            orderIndex = order++,
                            startMs = piece.startMs,
                            endMs = piece.endMs,
                            textEn = piece.text,
                            textKo = null,
                            chunkParentId = null,
                            wordCount = piece.wordCount,
                        ),
                        groupFirstIndex = groupFirstIndex,
                    )
                }
            }
        }
        return out
    }

    /** Reconstruct the full original sentence for the IMPRINT stage (spec §4). */
    suspend fun fullSentenceFor(line: SubLine): String {
        val group = line.chunkParentId ?: return line.textEn
        val siblings = lineDao.getBySource(line.sourceId)
            .filter { it.chunkParentId == group }
            .sortedBy { it.orderIndex }
        return if (siblings.isEmpty()) line.textEn else siblings.joinToString(" ") { it.textEn }
    }

    // ── Session building (spec §4) ──

    suspend fun buildSession(reviewGoal: Int, dailyGoal: Int, now: Long = System.currentTimeMillis()):
        List<com.shadowdict.domain.StudyItem> {
        val reviews = lineDao.reviewQueue(now, reviewGoal).map {
            com.shadowdict.domain.StudyItem(it, isReview = true)
        }
        val news = lineDao.newQueue(dailyGoal).map {
            com.shadowdict.domain.StudyItem(it, isReview = false)
        }
        return reviews + news
    }

    suspend fun dueReviewCount(now: Long = System.currentTimeMillis()): Int =
        lineDao.dueReviewCount(now)

    // ── Recording results ──

    suspend fun getLine(id: Long): SubLine? = lineDao.getById(id)

    /** Record a dictation attempt, updating first-try accuracy and best accuracy. */
    suspend fun recordAttempt(
        line: SubLine,
        userInput: String,
        accuracy: Float,
        hintLevel: Int,
        now: Long = System.currentTimeMillis(),
    ): SubLine {
        attemptDao.insert(
            Attempt(
                lineId = line.id,
                userInput = userInput,
                accuracy = accuracy,
                hintLevel = hintLevel,
                createdAt = now,
            ),
        )
        val updated = line.copy(
            attemptCount = line.attemptCount + 1,
            bestAccuracy = maxOf(line.bestAccuracy, accuracy),
            hintLevelUsed = maxOf(line.hintLevelUsed, hintLevel),
            // firstTryAccuracy is set once, on the first attempt, and never overwritten.
            firstTryAccuracy = line.firstTryAccuracy ?: accuracy,
            status = if (line.status == LineStatus.NEW) LineStatus.LEARNING else line.status,
        )
        lineDao.update(updated)
        return updated
    }

    /** Persist the learner's Korean meaning entered in the MEANING stage. */
    suspend fun saveMeaning(line: SubLine, meaning: String) {
        lineDao.update(line.copy(textKo = meaning))
    }

    suspend fun incrementReplay(line: SubLine): SubLine {
        val updated = line.copy(replayCount = line.replayCount + 1)
        lineDao.update(updated)
        return updated
    }

    /** Apply SRS scheduling when a line's dictation passes (spec §8). */
    suspend fun onLinePassed(
        line: SubLine,
        hintLevelUsed: Int,
        attemptsThisPass: Int,
        accuracy: Float,
        now: Long = System.currentTimeMillis(),
    ) {
        val updated = SrsScheduler.onPass(line, hintLevelUsed, attemptsThisPass, accuracy, now)
        lineDao.update(updated)
    }

    /** For an auto-generated source (no dictation) simply advance SRS on completion. */
    suspend fun onLineCompletedWithoutDictation(line: SubLine, now: Long = System.currentTimeMillis()) {
        val updated = SrsScheduler.onPass(line, hintLevelUsed = 0, attemptCount = 1, accuracy = 1f, now = now)
        lineDao.update(updated)
    }

    // ── Daily session / streak ──

    fun observeSession(date: String): Flow<DailySession?> = sessionDao.observe(date)
    fun observeRecentSessions(limit: Int): Flow<List<DailySession>> = sessionDao.observeRecent(limit)
    suspend fun recentSessions(limit: Int): List<DailySession> = sessionDao.recent(limit)

    /** Record progress for the day, marking completion when goals are met. */
    suspend fun recordDayProgress(
        date: LocalDate,
        newDone: Int,
        reviewDone: Int,
        goalCount: Int,
        studySeconds: Int,
        now: Long = System.currentTimeMillis(),
    ) {
        val key = date.toString()
        val existing = sessionDao.get(key)
        val newTotal = (existing?.newLinesDone ?: 0) + newDone
        val reviewTotal = (existing?.reviewLinesDone ?: 0) + reviewDone
        val completed = newTotal >= goalCount
        sessionDao.upsert(
            DailySession(
                date = key,
                newLinesDone = newTotal,
                reviewLinesDone = reviewTotal,
                goalCount = goalCount,
                isCompleted = completed || (existing?.isCompleted ?: false),
                usedFreeze = existing?.usedFreeze ?: false,
                studySeconds = (existing?.studySeconds ?: 0) + studySeconds,
                completedAt = if (completed) now else existing?.completedAt,
            ),
        )
    }

    /** Mark a day as covered by a streak freeze (spec §9). */
    suspend fun markFreezeUsed(date: String) {
        val existing = sessionDao.get(date)
        sessionDao.upsert(
            (existing ?: DailySession(date = date)).copy(usedFreeze = true),
        )
    }

    suspend fun frequentlyMissedInputs(limit: Int): List<String> = attemptDao.recentInputs(limit)
}
