package com.shadowdict.ui.addsource

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.shadowdict.core.subtitle.ParsedLine
import com.shadowdict.core.subtitle.SubtitleParser
import com.shadowdict.data.ShadowDictRepository
import com.shadowdict.data.local.entity.SourceType
import com.shadowdict.data.settings.SettingsRepository
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch

data class AddSourceUiState(
    val type: SourceType = SourceType.LOCAL_FILE,
    val title: String = "",
    val mediaUri: String? = null,        // SAF uri string or youtube videoId
    val mediaLabel: String? = null,      // filename / video id for display
    val subtitleFileName: String? = null,
    val isAutoGenerated: Boolean = false,
    val parsedLines: List<ParsedLine> = emptyList(),
    val previewError: String? = null,
    val saved: Boolean = false,
    val savedSourceId: Long? = null,
) {
    val canSave: Boolean
        get() = title.isNotBlank() && parsedLines.isNotEmpty() &&
            (type == SourceType.TEXT_ONLY || mediaUri != null)

    /** Dictation is unavailable for auto-generated subtitles (spec §2). */
    val dictationAvailable: Boolean get() = !isAutoGenerated
}

class AddSourceViewModel(
    private val repository: ShadowDictRepository,
    private val settingsRepository: SettingsRepository,
) : ViewModel() {

    private val _state = MutableStateFlow(AddSourceUiState())
    val state: StateFlow<AddSourceUiState> = _state.asStateFlow()

    fun setType(type: SourceType) {
        _state.value = _state.value.copy(type = type, parsedLines = emptyList(), previewError = null)
    }

    fun setTitle(title: String) {
        _state.value = _state.value.copy(title = title)
    }

    fun setAutoGenerated(value: Boolean) {
        _state.value = _state.value.copy(isAutoGenerated = value)
    }

    /** Local file chosen via SAF; caller has already taken a persistable permission. */
    fun setLocalMedia(uri: String, label: String) {
        _state.value = _state.value.copy(mediaUri = uri, mediaLabel = label)
    }

    /** Paste a YouTube URL; the video id is extracted. */
    fun setYouTubeUrl(url: String) {
        val id = extractVideoId(url)
        _state.value = _state.value.copy(mediaUri = id, mediaLabel = id ?: url)
    }

    /** Parse a chosen .srt/.vtt file's contents. */
    fun parseSubtitleContent(content: String, fileName: String) {
        val lines = SubtitleParser.parse(content)
        _state.value = if (lines.isEmpty()) {
            _state.value.copy(previewError = "자막을 해석하지 못했어요. 파일 형식을 확인해 주세요.")
        } else {
            _state.value.copy(
                parsedLines = lines,
                subtitleFileName = fileName,
                previewError = null,
            )
        }
    }

    /** Build lines from pasted plain text (TEXT_ONLY source). */
    fun parsePlainText(text: String) {
        val lines = text.split("\n")
            .map { it.trim() }
            .filter { it.isNotEmpty() }
            .mapIndexed { i, t ->
                // No real timings; TTS drives playback (spec §2).
                ParsedLine(i, i * 3000L, i * 3000L + 2500L, t)
            }
        _state.value = if (lines.isEmpty()) {
            _state.value.copy(previewError = "텍스트가 비어 있어요.")
        } else {
            _state.value.copy(parsedLines = lines, previewError = null)
        }
    }

    fun save() {
        val s = _state.value
        if (!s.canSave) return
        viewModelScope.launch {
            val threshold = settingsRepository.settings.first().chunkThreshold
            val id = repository.addSource(
                title = s.title.trim(),
                type = s.type,
                mediaUri = s.mediaUri,
                subtitleFileName = s.subtitleFileName,
                isAutoGenerated = s.isAutoGenerated,
                parsedLines = s.parsedLines,
                chunkThreshold = threshold,
            )
            _state.value = _state.value.copy(saved = true, savedSourceId = id)
        }
    }

    companion object {
        private val YT_PATTERNS = listOf(
            Regex("""v=([A-Za-z0-9_-]{11})"""),
            Regex("""youtu\.be/([A-Za-z0-9_-]{11})"""),
            Regex("""embed/([A-Za-z0-9_-]{11})"""),
            Regex("""shorts/([A-Za-z0-9_-]{11})"""),
        )

        fun extractVideoId(url: String): String? {
            for (p in YT_PATTERNS) {
                p.find(url)?.let { return it.groupValues[1] }
            }
            // Bare 11-char id.
            return if (Regex("""^[A-Za-z0-9_-]{11}$""").matches(url.trim())) url.trim() else null
        }
    }
}
