package com.shadowdict.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/** A learning source: one episode / clip (spec §3). */
@Entity(tableName = "sources")
data class Source(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val title: String,
    val type: SourceType,
    val mediaUri: String?,          // SAF persistable URI, or YouTube videoId
    val subtitleFileName: String?,  // original subtitle filename (for display)
    val isAutoGenerated: Boolean,   // true disables the dictation stage (spec §2)
    val totalLines: Int,
    val createdAt: Long,
    val lastStudiedAt: Long?,
)

enum class SourceType { LOCAL_FILE, YOUTUBE, TEXT_ONLY }
