package com.shadowdict.ui.study

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.shadowdict.core.scoring.DictationScorer
import com.shadowdict.core.scoring.ScoreResult
import com.shadowdict.core.subtitle.PlaybackTiming
import com.shadowdict.data.ShadowDictRepository
import com.shadowdict.data.local.entity.SourceType
import com.shadowdict.data.local.entity.SubLine
import com.shadowdict.data.settings.Settings
import com.shadowdict.data.settings.SettingsRepository
import com.shadowdict.domain.HintLadder
import com.shadowdict.domain.Stage
import com.shadowdict.domain.StageFlow
import com.shadowdict.domain.StudyItem
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch
import java.time.LocalDate

data class StudyUiState(
    val loading: Boolean = true,
    val finished: Boolean = false,
    val progressIndex: Int = 0,     // 1-based position in the session
    val total: Int = 0,
    val stage: Stage? = null,
    val stages: List<Stage> = emptyList(),
    val isReview: Boolean = false,
    val line: SubLine? = null,
    val fullSentence: String = "",
    val autoGenerated: Boolean = false,
    val mediaUri: String? = null,
    val sourceType: SourceType? = null,

    // LISTEN
    val listenReplays: Int = 0,
    val listenRequired: Int = StageFlow.LISTEN_REPLAYS_REQUIRED,

    // MEANING
    val meaningInput: String = "",

    // DICTATION
    val dictationInput: String = "",
    val scoreResult: ScoreResult? = null,
    val attemptNumber: Int = 1,
    val hintLevel: Int = 0,
    val hintText: String? = null,
    val revealAnswer: Boolean = false,

    // playback (screen owns the player and reacts to these)
    val playRequest: Int = 0,
    val playStartMs: Long = 0,
    val playEndMs: Long = 0,
    val playSpeed: Float = 1f,

    val strictPunctuation: Boolean = false,
) {
    val listenSatisfied: Boolean get() = listenReplays >= listenRequired
    val dictationPassed: Boolean get() = scoreResult?.passed == true
}

class StudyViewModel(
    private val repository: ShadowDictRepository,
    private val settingsRepository: SettingsRepository,
) : ViewModel() {

    private val _state = MutableStateFlow(StudyUiState())
    val state: StateFlow<StudyUiState> = _state.asStateFlow()

    private lateinit var settings: Settings
    private var items: List<StudyItem> = emptyList()
    private var index = 0
    private var stageIdx = 0
    private var attemptsThisLine = 0
    private var newDone = 0
    private var reviewDone = 0
    private var isYouTube = false

    fun start() {
        if (!_state.value.loading && items.isNotEmpty()) return
        viewModelScope.launch {
            settings = settingsRepository.settings.first()
            items = repository.buildSession(settings.reviewGoal, settings.dailyGoal)
            if (items.isEmpty()) {
                _state.value = StudyUiState(loading = false, finished = true)
            } else {
                index = 0
                loadCurrentLine()
            }
        }
    }

    private suspend fun loadCurrentLine() {
        val item = items[index]
        val line = repository.getLine(item.line.id) ?: item.line
        val source = repository.getSource(line.sourceId)
        isYouTube = source?.type == SourceType.YOUTUBE
        val autoGen = source?.isAutoGenerated ?: false
        val sourceType = source?.type
        val mediaUri = source?.mediaUri
        val stages = StageFlow.stagesFor(autoGen)
        stageIdx = 0
        attemptsThisLine = 0
        val full = repository.fullSentenceFor(line)

        _state.value = StudyUiState(
            loading = false,
            progressIndex = index + 1,
            total = items.size,
            stage = stages.first(),
            stages = stages,
            isReview = item.isReview,
            line = line,
            fullSentence = full,
            autoGenerated = autoGen,
            mediaUri = mediaUri,
            sourceType = sourceType,
            listenReplays = 0,
            strictPunctuation = settings.strictPunctuation,
            playSpeed = settings.playbackSpeed,
        )
        autoPlayIfNeeded()
    }

    // ── LISTEN ──

    fun onReplay() {
        val s = _state.value
        val line = s.line ?: return
        viewModelScope.launch { repository.incrementReplay(line) }
        _state.value = s.copy(listenReplays = s.listenReplays + 1)
        requestPlay()
    }

    // ── MEANING ──

    fun onMeaningChange(text: String) {
        _state.value = _state.value.copy(meaningInput = text)
    }

    fun confirmMeaning() {
        val s = _state.value
        val line = s.line ?: return
        if (s.meaningInput.isNotBlank()) {
            viewModelScope.launch { repository.saveMeaning(line, s.meaningInput.trim()) }
        }
        advanceStage()
    }

    // ── DICTATION ──

    fun onDictationChange(text: String) {
        _state.value = _state.value.copy(dictationInput = text)
    }

    fun submitDictation() {
        val s = _state.value
        val line = s.line ?: return
        val result = DictationScorer.score(line.textEn, s.dictationInput, s.strictPunctuation)
        attemptsThisLine++
        viewModelScope.launch {
            repository.recordAttempt(line, s.dictationInput, result.accuracy, s.hintLevel)
            if (result.passed) {
                repository.onLinePassed(line, s.hintLevel, attemptsThisLine, result.accuracy)
            }
        }
        val nextAttempt = s.attemptNumber + if (result.passed) 0 else 1
        val hintLevel = if (result.passed) s.hintLevel else HintLadder.levelForAttempt(nextAttempt)
        _state.value = s.copy(
            scoreResult = result,
            attemptNumber = nextAttempt,
            hintLevel = hintLevel,
        )
    }

    fun useHint() {
        val s = _state.value
        val line = s.line ?: return
        val level = s.hintLevel.coerceAtLeast(HintLadder.levelForAttempt(s.attemptNumber))
        val text = HintLadder.mask(line.textEn, level)
        val slow = HintLadder.autoSlow(level)
        _state.value = s.copy(
            hintText = text,
            hintLevel = level,
            revealAnswer = HintLadder.revealsAnswer(level),
            playSpeed = if (slow) 0.75f else s.playSpeed,
        )
    }

    /** Clear the last score so the user can retype after a failed attempt. */
    fun retryDictation() {
        _state.value = _state.value.copy(scoreResult = null, dictationInput = "")
        requestPlay()
    }

    // ── Stage navigation ──

    fun advanceStage() {
        val s = _state.value
        val stages = s.stages
        if (stageIdx < stages.lastIndex) {
            stageIdx++
            _state.value = s.copy(
                stage = stages[stageIdx],
                scoreResult = null,
                dictationInput = "",
                meaningInput = "",
                hintText = null,
                hintLevel = 0,
                revealAnswer = false,
                attemptNumber = 1,
            )
            autoPlayIfNeeded()
        } else {
            finishLine()
        }
    }

    private fun finishLine() {
        val s = _state.value
        if (s.isReview) reviewDone++ else newDone++
        val line = s.line
        viewModelScope.launch {
            if (s.autoGenerated && line != null) {
                repository.onLineCompletedWithoutDictation(line)
            }
            repository.recordDayProgress(
                date = LocalDate.now(),
                newDone = if (s.isReview) 0 else 1,
                reviewDone = if (s.isReview) 1 else 0,
                goalCount = settings.dailyGoal,
                studySeconds = 0,
            )
        }
        if (index < items.lastIndex) {
            index++
            viewModelScope.launch { loadCurrentLine() }
        } else {
            _state.value = s.copy(finished = true)
        }
    }

    // ── playback helpers ──

    fun requestPlay() {
        val s = _state.value
        val line = s.line ?: return
        _state.value = s.copy(
            playRequest = s.playRequest + 1,
            playStartMs = PlaybackTiming.paddedStart(line.startMs, isYouTube),
            playEndMs = PlaybackTiming.paddedEnd(line.endMs, isYouTube),
        )
    }

    private fun autoPlayIfNeeded() {
        when (_state.value.stage) {
            Stage.LISTEN, Stage.DICTATION, Stage.IMPRINT -> requestPlay()
            else -> Unit
        }
    }
}
