package com.shadowdict.youtube

import com.shadowdict.core.subtitle.ParsedLine
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONArray
import java.net.HttpURLConnection
import java.net.URL

/**
 * Best-effort on-device fetch of a YouTube video's caption track (spec §2/§6 note).
 *
 * YouTube exposes no official caption API, so this scrapes the watch page for the
 * `captionTracks` list inside `ytInitialPlayerResponse`, then downloads the chosen
 * track's timedtext XML. It is inherently fragile — YouTube can change the page or
 * gate captions — so callers must handle [Result.Failure] by falling back to a
 * user-supplied `.srt`.
 *
 * Auto-generated ("asr") tracks are flagged so the dictation stage can be disabled
 * (their punctuation/words are unreliable, spec §2).
 */
object YouTubeCaptionFetcher {

    private const val USER_AGENT =
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
            "(KHTML, like Gecko) Chrome/122.0 Safari/537.36"

    sealed interface Result {
        data class Success(
            val lines: List<ParsedLine>,
            val isAutoGenerated: Boolean,
            val languageCode: String,
        ) : Result

        data class Failure(val reason: String) : Result
    }

    suspend fun fetch(videoId: String, preferredLang: String = "en"): Result =
        withContext(Dispatchers.IO) {
            try {
                val watchHtml = httpGet(
                    "https://www.youtube.com/watch?v=$videoId&hl=en&bpctr=9999999999",
                ) ?: return@withContext Result.Failure("영상 페이지를 불러오지 못했어요.")

                val tracks = extractCaptionTracks(watchHtml)
                    ?: return@withContext Result.Failure(
                        "이 영상에는 사용할 수 있는 자막이 없어요. (자막 없는 영상이거나 유튜브가 막았을 수 있어요)",
                    )

                val track = chooseTrack(tracks, preferredLang)
                    ?: return@withContext Result.Failure("자막 트랙을 고르지 못했어요.")

                val xml = httpGet(track.baseUrl)
                    ?: return@withContext Result.Failure("자막 내용을 내려받지 못했어요.")

                val lines = parseTimedText(xml)
                if (lines.isEmpty()) {
                    return@withContext Result.Failure("자막을 해석했지만 내용이 비어 있어요.")
                }
                Result.Success(lines, track.isAsr, track.languageCode)
            } catch (e: Exception) {
                Result.Failure("자막을 가져오는 중 문제가 생겼어요: ${e.message}")
            }
        }

    private data class Track(
        val baseUrl: String,
        val languageCode: String,
        val isAsr: Boolean,
    )

    /** Pull the `captionTracks` JSON array out of the watch page and parse it. */
    private fun extractCaptionTracks(html: String): List<Track>? {
        val key = "\"captionTracks\":"
        val keyIndex = html.indexOf(key)
        if (keyIndex < 0) return null
        val arrayStart = html.indexOf('[', keyIndex)
        if (arrayStart < 0) return null
        val arrayEnd = matchingBracket(html, arrayStart)
        if (arrayEnd < 0) return null

        val json = html.substring(arrayStart, arrayEnd + 1)
        return runCatching {
            val arr = JSONArray(json)
            (0 until arr.length()).mapNotNull { i ->
                val obj = arr.getJSONObject(i)
                val baseUrl = obj.optString("baseUrl").takeIf { it.isNotEmpty() }
                    ?: return@mapNotNull null
                Track(
                    baseUrl = baseUrl,
                    languageCode = obj.optString("languageCode", "en"),
                    isAsr = obj.optString("kind") == "asr",
                )
            }
        }.getOrNull()?.takeIf { it.isNotEmpty() }
    }

    /** Prefer the requested language; a human track over ASR when both exist. */
    private fun chooseTrack(tracks: List<Track>, preferredLang: String): Track? {
        val langMatches = tracks.filter { it.languageCode.startsWith(preferredLang, ignoreCase = true) }
        val pool = langMatches.ifEmpty { tracks }
        return pool.firstOrNull { !it.isAsr } ?: pool.firstOrNull()
    }

    /** Parse timedtext XML (`<text start="1.2" dur="3.4">…</text>`) into lines. */
    private fun parseTimedText(xml: String): List<ParsedLine> {
        val regex = Regex("""<text start="([\d.]+)"(?:\s+dur="([\d.]+)")?[^>]*>(.*?)</text>""",
            RegexOption.DOT_MATCHES_ALL)
        val result = ArrayList<ParsedLine>()
        var order = 0
        for (m in regex.findAll(xml)) {
            val start = (m.groupValues[1].toDoubleOrNull() ?: continue)
            val dur = m.groupValues[2].toDoubleOrNull() ?: 2.0
            val text = decodeXml(m.groupValues[3]).replace(Regex("\\s+"), " ").trim()
            if (text.isEmpty()) continue
            val startMs = (start * 1000).toLong()
            val endMs = ((start + dur) * 1000).toLong()
            result.add(ParsedLine(order++, startMs, endMs, text))
        }
        return result
    }

    private fun decodeXml(input: String): String = input
        .replace("&amp;", "&")
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&quot;", "\"")
        .replace("&#39;", "'")
        .replace("&#34;", "\"")
        .replace(Regex("<[^>]+>"), " ")

    /** Index of the ']' matching the '[' at [openIndex], or -1. */
    private fun matchingBracket(s: String, openIndex: Int): Int {
        var depth = 0
        var i = openIndex
        var inString = false
        while (i < s.length) {
            val c = s[i]
            when {
                inString -> if (c == '\\') i++ else if (c == '"') inString = false
                c == '"' -> inString = true
                c == '[' -> depth++
                c == ']' -> {
                    depth--
                    if (depth == 0) return i
                }
            }
            i++
        }
        return -1
    }

    private fun httpGet(urlString: String): String? {
        val conn = (URL(urlString).openConnection() as HttpURLConnection).apply {
            requestMethod = "GET"
            connectTimeout = 15_000
            readTimeout = 15_000
            instanceFollowRedirects = true
            setRequestProperty("User-Agent", USER_AGENT)
            setRequestProperty("Accept-Language", "en-US,en;q=0.9")
            // Skip the EU consent interstitial that otherwise hides the player response.
            setRequestProperty("Cookie", "CONSENT=YES+1")
        }
        return try {
            if (conn.responseCode !in 200..299) null
            else conn.inputStream.bufferedReader().use { it.readText() }
        } finally {
            conn.disconnect()
        }
    }
}
